//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tradex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_conceptoventa
    {
        public int idconcepto { get; set; }
        public int idconfig { get; set; }
        public string descripcion { get; set; }
        public int idconceptofin { get; set; }
        public Nullable<int> idcuentacont { get; set; }
        public string codigo { get; set; }
        public bool enexperimento { get; set; }
    }
}
