//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tradex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fac_Talon
    {
        public int idtalon { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int idformato { get; set; }
        public int posicion { get; set; }
        public int CharBefore { get; set; }
        public int Charafter { get; set; }
        public int idtipotalon { get; set; }
    }
}
