//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tradex.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class facturasEntities : DbContext
    {
        public facturasEntities()
            : base("name=facturasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fac_Talon> Fac_Talon { get; set; }
        public virtual DbSet<gen_producto> gen_producto { get; set; }
        public virtual DbSet<inv_documento> inv_documento { get; set; }
        public virtual DbSet<inv_movimiento> inv_movimiento { get; set; }
        public virtual DbSet<gen_usuario> gen_usuario { get; set; }
        public virtual DbSet<gen_medida> gen_medida { get; set; }
        public virtual DbSet<fac_conceptoventa> fac_conceptoventa { get; set; }
    }
}
