//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Tradex.Models
{
    public partial class gen_entidad
    {
        public gen_entidad()
        {
            this.inv_documentoserv = new HashSet<inv_documentoserv>();
        }
    
        public int identidad { get; set; }
        public string codigo { get; set; }
        public string codigoreu { get; set; }
        public string nombre { get; set; }
        public string abreviatura { get; set; }
        public string direccion { get; set; }
        public bool activo { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string NIT { get; set; }
        public string IRCC { get; set; }
        public string provincia { get; set; }
        public string pais { get; set; }
    
        public virtual ICollection<inv_documentoserv> inv_documentoserv { get; set; }
    }
}
