//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tradex.Models
{
    public partial class gen_unidadcontable
    {
        public gen_unidadcontable()
        {
            this.gen_almacen = new HashSet<gen_almacen>();
            this.inv_configconceptocta = new HashSet<inv_configconceptocta>();
        }
    
        public int idunidad { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
        public string Direccion { get; set; }
        public string DirCorreo { get; set; }
        public Nullable<int> idnae { get; set; }
        public Nullable<int> iddpa { get; set; }
        public Nullable<int> idreup { get; set; }
    
        public virtual ICollection<gen_almacen> gen_almacen { get; set; }
        public virtual ICollection<inv_configconceptocta> inv_configconceptocta { get; set; }
        public virtual inv_configgeneral inv_configgeneral { get; set; }
    }
}
