//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Tradex.Models
{
    public partial class gen_moneda
    {
        public gen_moneda()
        {
            this.gen_tasacambio = new HashSet<gen_tasacambio>();
            this.inv_documentoserv = new HashSet<inv_documentoserv>();
        }
    
        public int idmoneda { get; set; }
        public string nombre { get; set; }
        public string sigla { get; set; }
        public int tipomoneda { get; set; }
        public bool MantieneValorTasa { get; set; }
        public int factor { get; set; }
    
        public virtual ICollection<gen_tasacambio> gen_tasacambio { get; set; }
        public virtual ICollection<inv_documentoserv> inv_documentoserv { get; set; }
    }
}
