//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tradex.Models
{
    public partial class gen_tasacambio
    {
        public gen_tasacambio()
        {
            this.inv_documentoserv = new HashSet<inv_documentoserv>();
        }
    
        public int idtasa { get; set; }
        public int idmoneda { get; set; }
        public DateTime fechacambio { get; set; }
        public decimal tasacambio { get; set; }
        public string origen { get; set; }
        public int tipotasa { get; set; }
        public int idusuario { get; set; }
        public Nullable<byte> idsubsistema { get; set; }
    
        public virtual gen_moneda gen_moneda { get; set; }
        public virtual ICollection<inv_documentoserv> inv_documentoserv { get; set; }
    }
}
