//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Tradex.Models
{
    public partial class gen_periodo
    {
        public int idperiodo { get; set; }
        public byte idejercicio { get; set; }
        public string nombre { get; set; }
        public DateTime inicio { get; set; }
        public DateTime fin { get; set; }
        public bool enuso { get; set; }
    }
}
