//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tradex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_documento
    {
        public inv_documento()
        {
            this.inv_movimiento = new HashSet<inv_movimiento>();
        }
    
        public int iddocumento { get; set; }
        public int numero { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> sumacantidad { get; set; }
        public Nullable<decimal> sumaimporte { get; set; }
        public int idunidad { get; set; }
        public int idestado { get; set; }
        public int idusuario { get; set; }
        public Nullable<decimal> sumaexistencia { get; set; }
        public int idconcepto { get; set; }
        public string numctrl { get; set; }
        public Nullable<byte> idsubsistema { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idusrconfirmar { get; set; }
        public long crc { get; set; }
    
        public virtual ICollection<inv_movimiento> inv_movimiento { get; set; }
        public virtual gen_usuario gen_usuario { get; set; }
        public virtual gen_usuario gen_usuario1 { get; set; }
    }
}
