//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Tradex.Models
{
    public partial class inv_concepto
    {
        public int idconcepto { get; set; }
        public int idregdocum { get; set; }
        public Nullable<int> idcriterio { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int idcategoria { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
