//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Tradex.Models
{
    public partial class inv_documentoserv
    {
        public int iddocumento { get; set; }
        public int identidad { get; set; }
        public int idservicio { get; set; }
        public int idmoneda { get; set; }
        public Nullable<int> idtasa { get; set; }
        public decimal importe { get; set; }
        public int iddocumentoserv { get; set; }
        public long crc { get; set; }
    
        public virtual gen_entidad gen_entidad { get; set; }
        public virtual gen_moneda gen_moneda { get; set; }
        public virtual gen_tasacambio gen_tasacambio { get; set; }
    }
}
