//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Tradex.Models
{
    public partial class inv_configgeneral
    {
        public int idunidad { get; set; }
        public Nullable<DateTime> fecha { get; set; }
        public Nullable<bool> sumactrl { get; set; }
        public Nullable<bool> usamlc { get; set; }
        public Nullable<bool> usamn { get; set; }
        public bool mostrarvalid { get; set; }
        public bool obligcompra { get; set; }
        public bool obligventa { get; set; }
        public bool obligventatrab { get; set; }
        public bool usalote { get; set; }
        public bool iva { get; set; }
    
        public virtual gen_unidadcontable gen_unidadcontable { get; set; }
    }
}
