//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tradex.Models
{
    public partial class inv_configconceptocta
    {
        public int idconcepto { get; set; }
        public int idunidad { get; set; }
        public int idcuenta { get; set; }
    
        public virtual con_cuenta con_cuenta { get; set; }
        public virtual gen_unidadcontable gen_unidadcontable { get; set; }
    }
}
