//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Tradex.Models
{
    public partial class TradexEntities : DbContext
    {
        public TradexEntities()
            : base("name=TradexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<con_cuenta> con_cuenta { get; set; }
        public virtual DbSet<gen_entidad> gen_entidad { get; set; }
        public virtual DbSet<gen_moneda> gen_moneda { get; set; }
        public virtual DbSet<gen_producto> gen_producto { get; set; }
        public virtual DbSet<gen_tasacambio> gen_tasacambio { get; set; }
        public virtual DbSet<inv_concepto> inv_concepto { get; set; }
        public virtual DbSet<inv_configconceptocta> inv_configconceptocta { get; set; }
        public virtual DbSet<inv_documentoserv> inv_documentoserv { get; set; }
        public virtual DbSet<gen_almacen> gen_almacen { get; set; }
        public virtual DbSet<gen_unidadcontable> gen_unidadcontable { get; set; }
        public virtual DbSet<gen_periodo> gen_periodo { get; set; }
        public virtual DbSet<inv_configgeneral> inv_configgeneral { get; set; }
        public virtual DbSet<gen_medida> gen_medida { get; set; }
    }
}
