//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Tradex.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("202")]
        public string codigoinv {
            get {
                return ((string)(this["codigoinv"]));
            }
            set {
                this["codigoinv"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("244")]
        public string almacenes {
            get {
                return ((string)(this["almacenes"]));
            }
            set {
                this["almacenes"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("010")]
        public string unidades {
            get {
                return ((string)(this["unidades"]));
            }
            set {
                this["unidades"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("6")]
        public string filaInicio {
            get {
                return ((string)(this["filaInicio"]));
            }
            set {
                this["filaInicio"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("15")]
        public string filaFin {
            get {
                return ((string)(this["filaFin"]));
            }
            set {
                this["filaFin"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Factura")]
        public string hojaExcel {
            get {
                return ((string)(this["hojaExcel"]));
            }
            set {
                this["hojaExcel"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("B")]
        public string columnaCodigo {
            get {
                return ((string)(this["columnaCodigo"]));
            }
            set {
                this["columnaCodigo"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("C")]
        public string columnaUm {
            get {
                return ((string)(this["columnaUm"]));
            }
            set {
                this["columnaUm"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("D")]
        public string columnadescripcion {
            get {
                return ((string)(this["columnadescripcion"]));
            }
            set {
                this["columnadescripcion"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("G")]
        public string columnaCantidad {
            get {
                return ((string)(this["columnaCantidad"]));
            }
            set {
                this["columnaCantidad"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("L")]
        public string columnaImporteCUC {
            get {
                return ((string)(this["columnaImporteCUC"]));
            }
            set {
                this["columnaImporteCUC"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("M")]
        public string columnaImporteMN {
            get {
                return ((string)(this["columnaImporteMN"]));
            }
            set {
                this["columnaImporteMN"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("B")]
        public string columnaInicio {
            get {
                return ((string)(this["columnaInicio"]));
            }
            set {
                this["columnaInicio"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("M")]
        public string columnaFin {
            get {
                return ((string)(this["columnaFin"]));
            }
            set {
                this["columnaFin"] = value;
            }
        }
    }
}
